### ISSUE TITLE
typeCoverageProvider server capability

### ISSUE THREAD

**Issue by mroch** [stevearc/flow-coverage.nvim#1]
hi, I'm from the Flow team and just came across this. cool :)

I noticed this comment:
https://github.com/stevearc/flow-coverage.nvim/blob/fbbe7fac1ff81d7b2ebfd8492ec4f113e13ae1e3/lua/flow.lua#L91-L92

just wanted to note that flow sets `"typeCoverageProvider": true` in the server capabilities. I'm not sure if it's possible to extend neovim's protocol (https://github.com/neovim/neovim/blob/ec4731d982031e363a59efd4566fc72234bb43c8/runtime/lua/vim/lsp/protocol.lua#L922) for custom commands though.

**Comment by stevearc** [comment]
Thanks for the tip! It looks like we can't use `resolved_capabilities` without making changes to Neovim core, but with your pointer I found that I could pull it directly off of `client.server_capabilities`!
